version: '3.8'

services:

  itemservice:
    build:
      context: ./ItemService
    container_name: itemservice
    ports:
      - "5001:8080"

  orderservice:
    build:
      context: ./OrderService
    container_name: orderservice
    ports:
      - "5002:8080"

  paymentservice:
    build:
      context: ./PaymentService
    container_name: paymentservice
    ports:
      - "5003:8080"

  apigateway:
    build:
      context: ./APIGateway
    container_name: apigateway
    ports:
      - "7000:8080"
    depends_on:
      - itemservice
      - orderservice
      - paymentservice